### ISSUE TITLE
 Error: The requested platform 'zWavePlatform' was not registered by any plugin.

### ISSUE THREAD

**Issue by slider973** [velocityzen/homebridge-platform-zwave#12]
![image](https://user-images.githubusercontent.com/15629276/85227081-509e9000-b3db-11ea-8e65-1f33787d8808.png)

![image](https://user-images.githubusercontent.com/15629276/85227097-71ff7c00-b3db-11ea-8d69-324a3e462d71.png)

this plugin not working or install it's to hardest

**Comment by velocityzen** [comment]
@slider973 you didn't install openzwave properly. Check #2 for solution
